from dataclasses import dataclass
from constants import *

@dataclass
class TestCase:
    sec: SECURITY_LEVEL
    field: FIELD_SIZE
    sharing: SHARING_SCHEME
    variant: SIG_VARIANT

test_cases = [
    TestCase(SECURITY_LEVEL.L1, FIELD_SIZE.GF16, SHARING_SCHEME.LIN_ADD_TRAD, SIG_VARIANT.FAST),
    TestCase(SECURITY_LEVEL.L1, FIELD_SIZE.GF16, SHARING_SCHEME.LIN_ADD_TRAD, SIG_VARIANT.SHORT),

    TestCase(SECURITY_LEVEL.L1, FIELD_SIZE.GF251, SHARING_SCHEME.LIN_ADD_TRAD, SIG_VARIANT.FAST),
    TestCase(SECURITY_LEVEL.L1, FIELD_SIZE.GF251, SHARING_SCHEME.LIN_ADD_TRAD, SIG_VARIANT.SHORT),

    TestCase(SECURITY_LEVEL.L1, FIELD_SIZE.GF256, SHARING_SCHEME.LIN_ADD_TRAD, SIG_VARIANT.FAST),
    TestCase(SECURITY_LEVEL.L1, FIELD_SIZE.GF256, SHARING_SCHEME.LIN_ADD_TRAD, SIG_VARIANT.SHORT),

    TestCase(SECURITY_LEVEL.L5, FIELD_SIZE.GF16, SHARING_SCHEME.LIN_ADD_TRAD, SIG_VARIANT.FAST),
    TestCase(SECURITY_LEVEL.L5, FIELD_SIZE.GF16, SHARING_SCHEME.LIN_ADD_TRAD, SIG_VARIANT.SHORT),

    TestCase(SECURITY_LEVEL.L5, FIELD_SIZE.GF251, SHARING_SCHEME.LIN_ADD_TRAD, SIG_VARIANT.FAST),
    TestCase(SECURITY_LEVEL.L5, FIELD_SIZE.GF251, SHARING_SCHEME.LIN_ADD_TRAD, SIG_VARIANT.SHORT),
    
    TestCase(SECURITY_LEVEL.L5, FIELD_SIZE.GF256, SHARING_SCHEME.LIN_ADD_TRAD, SIG_VARIANT.FAST),
    TestCase(SECURITY_LEVEL.L5, FIELD_SIZE.GF256, SHARING_SCHEME.LIN_ADD_TRAD, SIG_VARIANT.SHORT),
]